export const tickets = [
  {
    ticketNo: 1234,
    subject: "Login issue",
    status: "In Progress",
    supportBy: "Tech support",
    date: "13/08/24",
    rate: 3,
  },
  {
    ticketNo: 1124,
    subject: "New ticket issue",
    status: "On hold",
    supportBy: "Operation Team",
    date: "14/08/24",
    rate: 2,
  },
  {
    ticketNo: 1224,
    subject: "New request",
    status: "Closed",
    supportBy: "Tech support",
    date: "13/08/24",
    rate: 4,
  },
  {
    ticketNo: 1244,
    subject: "Ticket submission",
    status: "In Progress",
    supportBy: "Operation Team",
    date: "14/08/24",
    rate: 5,
  },
  {
    ticketNo: 1114,
    subject: "Login issue",
    status: "In Progress",
    supportBy: "Tech support",
    date: "03/08/24",
    rate: 1,
  },
];
